import { generateId } from './utils';

export class DddCore {}

/** Interface of DDD-core error */
export interface DddCoreErrorI {
  /** Identifier of error, auto-generated by 'generateId' function of options if not passed */
  id?: string;
  /** Type of error (e.g. "Validation", "VariantViolation") */
  type: string;
  /** Error name (e.g. "UserNotFoundError", "OrderCannotBeCancelledError") */
  name: string;
  /** Error message */
  message: string;
  /** Client-facing friendly message (i18n ready) */
  userMessage?: string;
  /** Error code (e.g. "USER_NOT_FOUND", "ORDER_INVALID_STATE") */
  code: string;
  /** More granular error code (e.g. "EMAIL_TAKEN", "PAYMENT_DECLINED") */
  subCode?: string;
  /** HTTP status */
  status?: number;
  /** Error details (fields or metadata) */
  details?: ErrorDetails;
  /** Cause of error (for chaining) */
  cause?: unknown;
  /** Stack trace of error (for debugging), overwrites 'Error.captureStackTrace' */
  stack?: string;
  /** ISO string timestamp of error, default 'new Date().toISOString()' */
  timestamp?: string;
  /** Trace id for microservices */
  traceId?: string;
  /** true = expected/handled error (default false) */
  isOperational?: boolean;
  /** Useful for background jobs, queues, etc. (default false) */
  retryable?: boolean;
  /** DDD context (e.g. "user", "order", "payment") */
  domain?: string;
  /** Extra context that is NOT metadata (e.g. userId, orderId) */
  context?: Record<string, unknown>;
}

/** Error details of DDD-core error (fields or metadata) */
export interface ErrorDetails {
  /** Single field errors (validation errors) */
  fieldErrors?: FieldError[];
  /** Metadata object of error */
  metadata?: Record<string, unknown>;
}

/** Validation error single field details */
export interface FieldError {
  /** Field of error */
  field: string;
  /** Error message of field */
  message: string;
  /** Error code of field */
  code?: string;
  /** Value of the field */
  value?: unknown;
  /** Constraint of validation (e.g. "isEmail", "minLength", "isPositive") */
  constraint?: string;
}

export class DddCoreError extends Error {
  /** Identifier of error */
  readonly id: string;
  /** Type of error (e.g. "Validation", "VariantViolation") */
  readonly type: string;
  /** Client-facing friendly message (i18n ready) */
  readonly userMessage?: string;
  /** Error code (e.g. "USER_NOT_FOUND", "ORDER_INVALID_STATE") */
  readonly code: string;
  /** More granular error code (e.g. "EMAIL_TAKEN", "PAYMENT_DECLINED") */
  readonly subCode?: string;
  /** HTTP status */
  readonly status?: number;
  /** Error details (fields or metadata) */
  readonly details: ErrorDetails;
  /** ISO string timestamp of error */
  readonly timestamp: string;
  /** Trace id for microservices */
  readonly traceId?: string;
  /** true = expected/handled error (default false) */
  readonly isOperational: boolean;
  /** Useful for background jobs, queues, etc. (default false) */
  readonly retryable: boolean;
  /** DDD context (e.g. "user", "order", "payment") */
  readonly domain?: string;
  /** Extra context that is NOT metadata (e.g. userId, orderId) */
  readonly context: Record<string, unknown>;

  constructor(error: DddCoreErrorI) {
    // Pass to super
    super(error.message, { cause: error.cause });

    // Mandatory fields
    this.id = error.id ?? generateId();
    this.type = error.type;
    this.name = error.name;
    this.code = error.code;
    this.timestamp = error.timestamp ?? new Date().toISOString();

    // Set to defualt fields
    this.details = error.details ?? {};
    this.context = error.context ?? {};
    this.isOperational = error.isOperational ?? false;
    this.retryable = error.retryable ?? false;

    // Optional fields
    if (error.userMessage) this.userMessage = error.userMessage;
    if (error.subCode) this.subCode = error.subCode;
    if (error.status) this.status = error.status;
    if (error.traceId) this.traceId = error.traceId;
    if (error.domain) this.domain = error.domain;
    if (error.stack) this.stack = error.stack;
  }
}
