export {
  DomainObject,
  type DomainObjectType,
  ValueObject,
  type ValueObjectStatic,
  type ValueObjectInstance,
  type ValueObjectRawType,
  type ValueObjectJson,
  Entity,
  type EntityStatic,
  type EntityInstance,
  type EntityStaticProps,
  type EntityInstanceProps,
  type EntityJson,
  AggregateRoot,
  type AggregateRootStatic,
  type AggregateRootInstance,
  type AggregateRootStaticProps,
  type AggregateRootInstanceProps,
  type AggregateRootJson,
  DomainError,
  ValidationError,
  InvariantError,
  type DomainErrorName,
  type DomainErrorJson,
  DomainEvent,
  type DomainEventStatic,
  type DomainEventInstance,
  type DomainEventJson,
  ReadOnlyDomainSet,
  DomainSet,
  MutableDomainSet,
  ReadOnlyDomainMap,
  DomainMap,
  MutableDomainMap,
  Specification,
  PredicateSpecification,
  AndSpecification,
  OrSpecification,
  NotSpecification,
  spec,
  type SpecificationStatic,
  type SpecificationInstance,
  type SpecificationType,
  type SpecificationJson,
  type PredicateSpecificationJson,
  type AndSpecificationJson,
  type OrSpecificationJson,
  type NotSpecificationJson,
  invariant,
  ensure,
} from './core';
export {
  withValueObject,
  WithValueObject,
  withEntity,
  WithEntity,
  withAggregateRoot,
  WithAggregateRoot,
} from './sigil-wrapper';
export { DomainResult, Ok, ok, Err, err } from './result';
export { type DddCoreOptions, updateDddCoreOptions } from './options';
