import { updateSigilOptions, type SigilOptions, DEFAULT_LABEL_REGEX } from '@vicin/sigil';
import equal from 'fast-deep-equal/es6';
import rfdc from 'rfdc';

export interface DddCoreOptions {
  isEqual?: (a: unknown, b: unknown) => boolean;
  deepClone?: <T>(input: T) => T;
  /**
   * Sigil options
   *
   * Validation rule applied to sigil labels before registration.
   *
   * - A function receives the label and must return `true` if valid.
   * - A `RegExp` must match the label.
   * - `null` disables validation entirely.
   *
   * Defaults to `null`.
   */
  sigilLabelValidation?: SigilOptions['labelValidation'];
  /**
   * Sigil options
   *
   * When enabled, non-decorated subclasses that would otherwise inherit an ancestor's label
   * will be assigned an autogenerated random label (so that explicit labels stay unique).
   */
  sigilAutofillLabels?: SigilOptions['autofillLabels'];
}

export const OPTIONS: Required<Omit<DddCoreOptions, 'sigilLabelValidation' | 'sigilAutofillLabels'>> = {
  isEqual: equal,
  deepClone: rfdc(),
};

export function updateDddCoreOptions(opts: DddCoreOptions) {
  if ('isEqual' in opts) {
    if (typeof opts.isEqual !== 'function') throw new TypeError("'updateDddOptions.isEqual' must be a function");
    OPTIONS.isEqual = opts.isEqual;
  }

  if ('deepClone' in opts) {
    if (typeof opts.deepClone !== 'function') throw new TypeError("'updateDddOptions.deepClone' must be a function");
    OPTIONS.deepClone = opts.deepClone;
  }

  if ('sigilLabelValidation' in opts) {
    const val = opts.sigilLabelValidation;
    if (val !== null && typeof val !== 'function' && !(val instanceof RegExp))
      throw new Error("'updateDddCoreOptions.sigilLabelValidation' must be null, function or RegExp");
    updateSigilOptions({ labelValidation: val });
  }

  if ('sigilAutofillLabels' in opts) {
    if (typeof opts.sigilAutofillLabels !== 'boolean')
      throw new Error("'updateDddCoreOptions.sigilAutofillLabels' must be boolean");
    updateSigilOptions({ autofillLabels: opts.sigilAutofillLabels });
  }
}

export function strict() {
  updateSigilOptions({ labelValidation: DEFAULT_LABEL_REGEX, autofillLabels: false });
}
