import {
  AttachSigil,
  generateId,
  Sigilify,
  withIdentityObject,
  type ExtendSigil,
  type sigil,
} from '../utils';
import type { DddCoreError, ErrorDetails } from './error';

/** Interface of DDD-core error */
export interface ErrorObjectOptions {
  /** Identifier of error, auto-generated by 'generateId' function of options if not passed */
  id?: string;
  /** Type of error (e.g. "Validation", "VariantViolation") */
  type: string;
  /** Error name (e.g. "UserNotFoundError", "OrderCannotBeCancelledError") */
  name: string;
  /** Error message */
  message: string;
  /** Client-facing friendly message (i18n ready) */
  userMessage?: string;
  /** Error code (e.g. "USER_NOT_FOUND", "ORDER_INVALID_STATE") */
  code: string;
  /** More granular error code (e.g. "EMAIL_TAKEN", "PAYMENT_DECLINED") */
  subCode?: string;
  /** HTTP status */
  status?: number;
  /** Error details (fields or metadata) */
  details?: ErrorDetails;
  /** Cause of error (for chaining) */
  cause?: unknown;
  /** Stack trace of error (for debugging), overwrites 'Error.captureStackTrace' */
  stack?: string;
  /** ISO string timestamp of error, default 'new Date().toISOString()' */
  timestamp?: string;
  /** Trace id for microservices */
  traceId?: string;
  /** true = expected/handled error (default false) */
  isOperational?: boolean;
  /** Useful for background jobs, queues, etc. (default false) */
  retryable?: boolean;
  /** DDD context (e.g. "user", "order", "payment") */
  domain?: string;
  /** Extra context that is NOT metadata (e.g. userId, orderId) */
  context?: { [k: string]: unknown };
}

const ErrorBase = Sigilify(Error, '@vicin/ddd-core.ErrorBase' as 'ErrorBase');

const IdentityObject = withIdentityObject('ErrorObject', ErrorBase);
type IdentityObject = InstanceType<typeof IdentityObject>;

@AttachSigil('@vicin/ddd-core.ErrorObject')
export abstract class ErrorObject extends IdentityObject {
  declare [sigil]: ExtendSigil<'ErrorObject', IdentityObject>;

  override get [Symbol.toStringTag]() {
    return 'ErrorObject';
  }

  /** Identifier of error */
  readonly id: string;
  /** Type of error (e.g. "Validation", "VariantViolation") */
  readonly type: string;
  /** Client-facing friendly message (i18n ready) */
  readonly userMessage?: string;
  /** Error code (e.g. "USER_NOT_FOUND", "ORDER_INVALID_STATE") */
  readonly code: string;
  /** More granular error code (e.g. "EMAIL_TAKEN", "PAYMENT_DECLINED") */
  readonly subCode?: string;
  /** HTTP status */
  readonly status?: number;
  /** Error details (fields or metadata) */
  readonly details: ErrorDetails;
  /** ISO string timestamp of error */
  readonly timestamp: string;
  /** Trace id for microservices */
  readonly traceId?: string;
  /** true = expected/handled error (default false) */
  readonly isOperational: boolean;
  /** Useful for background jobs, queues, etc. (default false) */
  readonly retryable: boolean;
  /** DDD context (e.g. "user", "order", "payment") */
  readonly domain?: string;
  /** Extra context that is NOT metadata (e.g. userId, orderId) */
  readonly context: Record<string, unknown>;

  constructor(error: ErrorObjectOptions) {
    // Pass to super
    super(error.message, { cause: error.cause });

    // Mandatory fields
    this.id = error.id ?? generateId();
    this.type = error.type;
    this.name = error.name;
    this.code = error.code;
    this.timestamp = error.timestamp ?? new Date().toISOString();

    // Set to defualt fields
    this.details = error.details ?? {};
    this.context = error.context ?? {};
    this.isOperational = error.isOperational ?? false;
    this.retryable = error.retryable ?? false;

    // Optional fields
    if (error.userMessage) this.userMessage = error.userMessage;
    if (error.subCode) this.subCode = error.subCode;
    if (error.status) this.status = error.status;
    if (error.traceId) this.traceId = error.traceId;
    if (error.domain) this.domain = error.domain;
    if (error.stack) this.stack = error.stack;
  }

  toId(): string {
    return this.id;
  }

  getState(): DddCoreError {
    return {
      // dentity & Metadata
      id: this.id,
      traceId: this.traceId,
      timestamp: this.timestamp,

      // Classification
      domain: this.domain,
      type: this.type,
      name: this.name,

      // Codes & Status
      status: this.status,
      code: this.code,
      subCode: this.subCode,

      // Messages
      message: this.message,
      userMessage: this.userMessage,

      // Operational Flags
      isOperational: this.isOperational,
      retryable: this.retryable,

      // Context & Debugging
      details: this.details,
      context: this.context,
      cause: this.cause,
      stack: this.stack,
    };
  }
}
